service: sls-blog-posts-api-lambda

provider:
  environment:
    ENV: ${opt:stage, 'local'}
    DB_URL: ${env:DB_URL, file(./env.yml):DB_URL}
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: ${opt:stage}

package:
  include:
    - config/**
    - handlers/**
    - helpers/**
    - models/**
    - node_modules/**
    - requestSchemas/**
    - responseSchemas/**
    - tests/**
    - utils/**
  exclude:
    - ./**

functions:
  getblogPosts:
    handler: handlers/blog.get
    events:
      - http:
          path: blog/
          method: get
  getSingleBlogPost:
    handler: handlers/blog.get
    events:
      - http:
          path: /blog/{id}
          method: get
  createBlogPost:
    handler: handlers/blog.post
    events:
      - http:
          path: /blog
          method: post
  updateBlogPost:
    handler: handlers/blog.patch
    events:
      - http:
          path: /blog/{id}
          method: patch
  deleteBlogPost:
    handler: handlers/blog.delete
    events:
      - http:
          path: /blog/{id}
          method: delete
  badRequest:
    handler: handlers/badRequest.main
    events:
      - http:
          path: /blog/{id}/{all+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
